catchErr = require('./catch_err')

exports = {
  catchErr
}
