catchErr = require('./catch_err')

module.exports = {
  catchErr
}
